# Auto-generated by splitting 5v5 copy.py -- see conversation history for the split rationale.

import sim_engine
from sim_engine import *
from players_data import *
from gui_app import run_gui_app
from web_app import run_web_gui_app

if __name__ == "__main__":
    # A packaged Windows build is the GUI application. Keep the interactive
    # terminal menu only when this source file is run directly without --gui.
    if getattr(sys, "frozen", False) or "--gui" in sys.argv:
        run_gui_app()
        sys.exit(0)

    # Historical teams (from your existing code)
    heat = make_heat_2013()
    heat2020 = make_heat_2020()
    warriors = make_warriors_2017()
    warriors2016 = make_warriors_2016()
    warriors2019 = make_warriors_2019()
    warriors2022 = make_warriors_2022()
    timberwolves2024 = make_timberwolves_2024()
    nuggets = make_nuggets_2024()
    bulls = make_bulls_1996()
    cavs2009 = make_cavs_2009()
    magic2009 = make_magic_2009()
    sixers2001 = make_76ers_2001()
    cavs = make_cavs_2016()
    cavs2017 = make_cavs_2017()
    cavs2018 = make_cavs_2018()
    raptors2016 = make_raptors_2016()
    heat2016 = make_heat_2016()
    hawks2016 = make_hawks_2016()
    celtics2016 = make_celtics_2016()
    hornets2016 = make_hornets_2016()
    pacers2016 = make_pacers_2016()
    pistons2016 = make_pistons_2016()
    pistons2004 = make_pistons_2004()
    rockets2016 = make_rockets_2016()
    spurs2016 = make_spurs_2016()
    grizzlies2016 = make_grizzlies_2016()
    thunder2016 = make_thunder_2016()
    mavs2016 = make_mavs_2016()
    clippers2016 = make_clippers_2016()
    blazers2016 = make_blazers_2016()
    lakers = make_lakers_2001()
    lakers2008 = make_lakers_2008()
    lakers1987 = make_lakers_1987()
    spurs = make_spurs_2014()
    heat2023 = make_heat_2023()
    nets = make_nets_2021()
    nets2022 = make_nets_2022()
    bucks = make_bucks_2021()
    rockets1994 = make_rockets_1994()
    rockets = make_rockets_2018()
    thunder2024 = make_thunder_2024()
    thunder = make_thunder_2026()
    lakers2020 = make_lakers_2020()
    lakers2026 = make_lakers_2026()
    celtics2024 = make_celtics_2024()
    celtics2020 = make_celtics_2020()
    celtics2022 = make_celtics_2022()
    celtics2012 = make_celtics_2012()
    celtics1987 = make_celtics_1987()
    celtics2008 = make_celtics_2008()
    celtics2018 = make_celtics_2018()
    spurs2026 = make_spurs_2026()
    mavs2024 = make_mavs_2024()
    mavs2026 = make_mavs_2026()
    thunder2012 = make_thunder_2012()
    raptors2018 = make_raptors_2018()
    raptors2019 = make_raptors_2019()
    jazz2021 = make_jazz_2021()
    clippers2015 = make_clippers_2015()
    clippers2014 = make_clippers_2014()
    grizzlies2022 = make_grizzlies_2022()
    clippers2021 = make_clippers_2021()
    clippers2024 = make_clippers_2024()
    pelicans2018 = make_pelicans_2018()
    thunder2018 = make_thunder_2018()
    sixers2019= make_sixers_2019()
    suns2021 = make_suns_2021()
    pacers2025 = make_pacers_2025()
    knicks2026 = make_knicks_2026()
    knicks2013 = make_knicks_2013()
    bulls2011 = make_bulls_2011()
    blazers2021 = make_blazers_2021()
    kings2023 = make_kings_2023()
    mavs2011 = make_mavs_2011()
    grizzlies2013 = make_grizzlies_2013()
    hawks2015 = make_hawks_2015()
    wizards2017 = make_wizards_2017()
    jazz2018 = make_jazz_2018()
    rockets2020 = make_rockets_2020()
    hawks2021 = make_hawks_2021()
    mavs2022 = make_mavs_2022()
    magic2024 = make_magic_2024()
    pelicans2024 = make_pelicans_2024()
    rockets2026 = make_rockets_2026()
    cavs2026 = make_cavs_2026()





    print("Select mode:")
    print("  1. Game")
    print("  2. AI fantasy draft")
    print("  3. Playoff series")
    print("  4. Full playoffs")
    print("  5. Fantasy draft playoffs")
    print("  6. GUI")
    print("  7. Olympic/FIBA tournament")


    mode = input("Enter 1, 2, 3, 4, 5, 6, or 7: ").strip()

    if mode == "7":
        run_olympic_tournament({factory().name: factory for factory in fantasy_team_factories()})

    elif mode == "6":
        run_gui_app()

    elif mode == "2":
        print("\nSelect fantasy pool:")
        print("  1. All simulator teams")
        print("  2. 2026 teams only")
        fantasy_choice = input("Enter 1 or 2: ").strip()
        run_fantasy_draft_and_game("2026 " if fantasy_choice in ("2", "2026") else None)

    elif mode == "5":
        run_fantasy_draft_playoffs()

    elif mode == "4":
        print("\nSelect playoff year:")
        print("  1. 2016")
        year_choice = input("Enter year option: ").strip()
        if year_choice not in ("1", "2016"):
            print("Only 2016 is available right now.")
        else:
            old_pause_after_series_games = sim_engine.PAUSE_AFTER_SERIES_GAMES
            sim_engine.PAUSE_AFTER_SERIES_GAMES = True
            run_2016_playoffs()
            sim_engine.PAUSE_AFTER_SERIES_GAMES = old_pause_after_series_games

    elif mode == "3":

    # Change these two factories to whatever matchup you want.
        apply_star_clutchness(
                    heat, heat2020, heat2023, warriors, warriors2016, warriors2019, warriors2022, timberwolves2024,
                    nuggets, bulls, cavs2009, magic2009, sixers2001, cavs, cavs2017, cavs2018, raptors2016, heat2016, hawks2016, celtics2016,
                    hornets2016, pacers2016, pistons2016, pistons2004, rockets2016, spurs2016, grizzlies2016, thunder2016,
                    mavs2016, clippers2016, blazers2016, lakers, lakers2008, lakers1987, spurs,
                    nets, nets2022, bucks, rockets1994, rockets, thunder2024, thunder, lakers2020, lakers2026, celtics2024, celtics2020, celtics2022, celtics2012, celtics1987, celtics2008,
                    celtics2018, spurs2026, thunder2012, raptors2018, raptors2019, jazz2021, clippers2015, clippers2014,
                    grizzlies2022, clippers2021, clippers2024, pelicans2018, thunder2018,
                    sixers2019, suns2021, pacers2025, knicks2026, knicks2013, bulls2011, blazers2021,
                    kings2023, mavs2011, grizzlies2013, hawks2015, wizards2017, jazz2018, rockets2020,
                    hawks2021, mavs2022, magic2024, pelicans2024, rockets2026, cavs2026,
                    mavs2026
            )
        run_best_of_7_series(make_thunder_2026, make_heat_2013)


    else:
        apply_star_clutchness(
                heat, heat2020, heat2023, warriors, warriors2016, warriors2019, warriors2022, timberwolves2024,
                nuggets, bulls, cavs2009, magic2009, sixers2001, cavs, cavs2017, cavs2018, raptors2016, heat2016, hawks2016, celtics2016,
                hornets2016, pacers2016, pistons2016, pistons2004, rockets2016, spurs2016, grizzlies2016, thunder2016,
                mavs2016, clippers2016, blazers2016, lakers, lakers2008, lakers1987, spurs,
                nets, nets2022, bucks, rockets1994, rockets, thunder2024, thunder, lakers2020, lakers2026, celtics2024, celtics2020, celtics2022, celtics2012, celtics1987, celtics2008,
                celtics2018, spurs2026, thunder2012, raptors2018, raptors2019, jazz2021, clippers2015, clippers2014,
                grizzlies2022, clippers2021, clippers2024, pelicans2018, thunder2018,
                sixers2019, suns2021, pacers2025, knicks2026, knicks2013, bulls2011, blazers2021,
                kings2023, mavs2011, grizzlies2013, hawks2015, wizards2017, jazz2018, rockets2020,
                hawks2021, mavs2022, magic2024, pelicans2024, rockets2026, cavs2026,
                mavs2026
        )
 
        teamA = celtics2018
        teamB = raptors2019
        simulate_game(teamA, teamB)

