# Auto-generated by splitting 5v5 copy.py -- see conversation history for the split rationale.

import sim_engine
from sim_engine import *
from players_data import *

class WebGuiOutputProxy:
    def __init__(self, broadcast):
        self.broadcast = broadcast
        self.buffer = ""
        self.scoreboard_pattern = re.compile(r"^(.+?) \| ([0-9]+:[0-9]{2}) \| (.+?): (\d+)\s+(.+?): (\d+)$")

    def write(self, text):
        if not text:
            return
        self.broadcast({"type": "log", "text": text})
        self.buffer += text
        while "\n" in self.buffer:
            line, self.buffer = self.buffer.split("\n", 1)
            self._maybe_scoreboard(line.strip())

    def flush(self):
        return

    def _maybe_scoreboard(self, line: str):
        match = self.scoreboard_pattern.match(line)
        if not match:
            return
        period, clock, team_a, score_a, team_b, score_b = match.groups()
        self.broadcast({
            "type": "scoreboard",
            "text": f"{period}  {clock}    {team_a} {score_a} - {score_b} {team_b}"
        })

def run_web_gui_app(tk_error: Exception = None):
    from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

    factories = gui_team_factories()
    team_names = list(factories.keys())
    gui_roster_swaps = {}
    gui_custom_team_factories = {}
    if len(team_names) < 2:
        print("Web GUI needs at least two available teams.")
        return

    clients = []
    clients_lock = threading.Lock()
    run_lock = threading.Lock()
    running = {"active": False}

    def broadcast(event: Dict):
        with clients_lock:
            live_clients = list(clients)
        for client_queue in live_clients:
            try:
                client_queue.put_nowait(event)
            except Exception:
                pass

    def run_selected_sim(mode: str, team_a_name: str, team_b_name: str):
        original_stdout = sys.stdout
        original_input = builtins.input
        original_sleep = sim_engine.SLEEP
        sys.stdout = WebGuiOutputProxy(broadcast)
        builtins.input = lambda prompt="": ""
        sim_engine.SLEEP = 0.06
        sim_engine.SIM_FAST_FORWARD = False
        sim_engine.SIM_JUMP_TARGET = None
        try:
            if mode == "Game":
                team_a = factories[team_a_name]()
                team_b = factories[team_b_name]()
                apply_star_clutchness(team_a, team_b)
                assign_player_badges(team_a)
                assign_player_badges(team_b)
                simulate_game(team_a, team_b)
            elif mode == "Playoff series":
                run_best_of_7_series(factories[team_a_name], factories[team_b_name])
            else:
                run_2016_playoffs()
        except Exception:
            traceback.print_exc()
        finally:
            sim_engine.SIM_FAST_FORWARD = False
            sim_engine.SIM_JUMP_TARGET = None
            sim_engine.SLEEP = original_sleep
            builtins.input = original_input
            sys.stdout = original_stdout
            with run_lock:
                running["active"] = False
            broadcast({"type": "status", "text": "Finished"})
            broadcast({"type": "log", "text": "\n[GUI] Simulation finished.\n"})

    teams_json = json.dumps(team_names)
    page = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>5v5 Simulator GUI</title>
  <style>
    body {{ margin: 0; font-family: Arial, sans-serif; background: #111827; color: #e5e7eb; }}
    .scoreboard {{ position: sticky; top: 0; z-index: 2; background: #020617; border-bottom: 1px solid #334155; padding: 18px 22px; text-align: center; font-size: 24px; font-weight: 800; }}
    .controls {{ display: grid; grid-template-columns: 170px 1fr 1fr auto auto; gap: 10px; padding: 14px; background: #1f2937; border-bottom: 1px solid #374151; }}
    select, button {{ font-size: 15px; padding: 10px; border-radius: 6px; border: 1px solid #475569; background: #0f172a; color: #f8fafc; }}
    button {{ cursor: pointer; background: #2563eb; border-color: #3b82f6; font-weight: 700; }}
    button.secondary {{ background: #334155; border-color: #475569; }}
    #status {{ padding: 8px 14px; color: #cbd5e1; background: #111827; }}
    #log {{ height: calc(100vh - 155px); overflow-y: auto; white-space: pre-wrap; padding: 16px; box-sizing: border-box; font-family: Consolas, Consolas, monospace; font-size: 13px; line-height: 1.45; background: #0b1120; }}
  </style>
</head>
<body>
  <div id="scoreboard" class="scoreboard">Select a mode and teams, then start the sim.</div>
  <div class="controls">
    <select id="mode">
      <option>Game</option>
      <option>Playoff series</option>
      <option>Full 2016 playoffs</option>
    </select>
    <select id="teamA"></select>
    <select id="teamB"></select>
    <button id="start">Start</button>
    <button id="clear" class="secondary">Clear</button>
  </div>
  <div id="status">Ready</div>
  <div id="log"></div>
  <script>
    const TEAMS = {teams_json};
    const mode = document.getElementById("mode");
    const teamA = document.getElementById("teamA");
    const teamB = document.getElementById("teamB");
    const log = document.getElementById("log");
    const status = document.getElementById("status");
    const scoreboard = document.getElementById("scoreboard");

    function fillTeams() {{
      TEAMS.forEach((name, index) => {{
        teamA.add(new Option(name, name));
        teamB.add(new Option(name, name));
        if (index === 1) teamB.value = name;
      }});
    }}

    function syncMode() {{
      const disabled = mode.value === "Full 2016 playoffs";
      teamA.disabled = disabled;
      teamB.disabled = disabled;
    }}

    function append(text) {{
      log.textContent += text;
      log.scrollTop = log.scrollHeight;
    }}

    new EventSource("/events").onmessage = event => {{
      const data = JSON.parse(event.data);
      if (data.type === "log") append(data.text);
      if (data.type === "scoreboard") scoreboard.textContent = data.text;
      if (data.type === "status") status.textContent = data.text;
    }};

    document.getElementById("start").onclick = async () => {{
      if (mode.value !== "Full 2016 playoffs" && teamA.value === teamB.value) {{
        status.textContent = "Pick two different teams.";
        return;
      }}
      log.textContent = "";
      scoreboard.textContent = "Starting simulation...";
      status.textContent = "Running...";
      const response = await fetch("/start", {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ mode: mode.value, teamA: teamA.value, teamB: teamB.value }})
      }});
      if (!response.ok) status.textContent = await response.text();
    }};

    document.getElementById("clear").onclick = () => {{
      log.textContent = "";
      scoreboard.textContent = "Select a mode and teams, then start the sim.";
      status.textContent = "Ready";
    }};

    mode.onchange = syncMode;
    fillTeams();
    syncMode();
  </script>
</body>
</html>"""

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, format, *args):
            return

        def do_GET(self):
            if self.path == "/events":
                client_queue = queue.Queue()
                with clients_lock:
                    clients.append(client_queue)
                self.send_response(200)
                self.send_header("Content-Type", "text/event-stream")
                self.send_header("Cache-Control", "no-cache")
                self.send_header("Connection", "keep-alive")
                self.end_headers()
                try:
                    client_queue.put({"type": "status", "text": "Ready"})
                    while True:
                        event = client_queue.get()
                        payload = f"data: {json.dumps(event)}\n\n".encode("utf-8")
                        self.wfile.write(payload)
                        self.wfile.flush()
                except Exception:
                    with clients_lock:
                        if client_queue in clients:
                            clients.remove(client_queue)
                return

            body = page.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_POST(self):
            if self.path != "/start":
                self.send_error(404)
                return
            length = int(self.headers.get("Content-Length", "0"))
            data = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
            mode = data.get("mode", "Game")
            team_a_name = data.get("teamA", team_names[0])
            team_b_name = data.get("teamB", team_names[1])
            with run_lock:
                if running["active"]:
                    self.send_response(409)
                    self.end_headers()
                    self.wfile.write(b"A simulation is already running.")
                    return
                if mode != "Full 2016 playoffs" and team_a_name == team_b_name:
                    self.send_response(400)
                    self.end_headers()
                    self.wfile.write(b"Pick two different teams.")
                    return
                running["active"] = True
            broadcast({"type": "log", "text": ""})
            broadcast({"type": "status", "text": "Running..."})
            thread = threading.Thread(target=run_selected_sim, args=(mode, team_a_name, team_b_name), daemon=True)
            thread.start()
            body = b'{"ok": true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

    server = None
    for port in range(8765, 8785):
        try:
            server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
            break
        except OSError:
            continue
    if server is None:
        print("Web GUI could not find an open local port.")
        return

    url = f"http://127.0.0.1:{server.server_address[1]}"
    if tk_error is not None:
        print(f"Tkinter unavailable ({tk_error}). Starting browser GUI instead.")
    print(f"5v5 Simulator GUI running at {url}")
    try:
        webbrowser.open(url)
    except Exception:
        pass
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nWeb GUI stopped.")
    finally:
        server.server_close()

